// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = ":root {\n  --reach-slider: 1;\n}\n\n[data-reach-slider-input] {\n  max-width: 100%;\n}\n\n[data-reach-slider-input][data-orientation=\"horizontal\"] {\n  height: 0.5rem;\n}\n\n[data-reach-slider-input][data-orientation=\"vertical\"] {\n  width: 0.5rem;\n  /* the height is somewhat arbitrary but necessary for vertical sliders for\n  basic functionality */\n  height: 250px;\n  max-height: 100%;\n}\n\n[data-reach-slider-input][data-disabled] {\n  opacity: 0.5;\n  pointer-events: none;\n}\n\n[data-reach-slider-track] {\n  position: relative;\n  border-radius: 0.25rem;\n  background: hsl(0, 0%, 95%);\n}\n\n[data-reach-slider-track][data-orientation=\"horizontal\"] {\n  width: 100%;\n  height: inherit;\n}\n\n[data-reach-slider-track][data-orientation=\"vertical\"] {\n  width: inherit;\n  height: 100%;\n}\n\n/* This pseudo element provides an invisible area that increases the touch\ntarget size of the track */\n[data-reach-slider-track]::before {\n  content: \"\";\n  position: absolute;\n}\n\n[data-reach-slider-track][data-orientation=\"horizontal\"]::before {\n  width: 100%;\n  height: 1.5rem;\n  top: calc(-0.5rem - 1px);\n  left: 0;\n}\n\n[data-reach-slider-track][data-orientation=\"vertical\"]::before {\n  width: 1.5rem;\n  height: 100%;\n  top: 0;\n  left: calc(-0.5rem - 1px);\n}\n\n[data-reach-slider-handle] {\n  width: 16px;\n  height: 16px;\n  background: #1159a6;\n  border-radius: 10px;\n  z-index: 1;\n  transform-origin: center;\n}\n\n[data-reach-slider-handle][aria-orientation=\"horizontal\"] {\n  top: 50%;\n  transform: translateY(-50%);\n}\n\n[data-reach-slider-handle][aria-orientation=\"horizontal\"]:focus {\n  transform: translateY(-50%);\n}\n\n[data-reach-slider-handle][aria-orientation=\"vertical\"] {\n  left: 50%;\n  transform: translateX(-50%);\n}\n\n[data-reach-slider-range] {\n  border-radius: inherit;\n  background: #1159a6;\n  left: 0;\n  bottom: 0;\n}\n\n[data-reach-slider-range][data-orientation=\"horizontal\"] {\n  height: 100%;\n}\n\n[data-reach-slider-range][data-orientation=\"vertical\"] {\n  width: 100%;\n}\n\n[data-reach-slider-marker] {\n  background: hsl(0, 0%, 50%);\n  transform-origin: center;\n}\n\n[data-reach-slider-marker][data-orientation=\"horizontal\"] {\n  top: 50%;\n  transform: translate(-50%, -50%);\n  width: 3px;\n  height: 0.75rem;\n}\n\n[data-reach-slider-marker][data-orientation=\"vertical\"] {\n  left: 50%;\n  transform: translate(-50%, -50%);\n  width: 0.75rem;\n  height: 3px;\n}\n\n[data-reach-slider-marker][data-state=\"at-value\"],\n[data-reach-slider-marker][data-state=\"under-value\"] {\n  /* */\n}\n\n/* TODO: Remove in 1.0 */\n[data-reach-slider-track-highlight] {\n  border-radius: inherit;\n  background: #1159a6;\n  left: 0;\n  bottom: 0;\n}\n\n[data-reach-slider-track-highlight][data-orientation=\"horizontal\"] {\n  height: 100%;\n}\n\n[data-reach-slider-track-highlight][data-orientation=\"vertical\"] {\n  width: 100%;\n}\n";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}